name: Deploy JSON Files to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (all branches)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build & generate JSON
        run: cargo run --release

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Switch to (or create) gh-pages branch
        run: |
          git fetch origin gh-pages:gh-pages || echo "no gh-pages yet"
          if git rev-parse --verify gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

      - name: Clean branch contents
        run: |
          git rm -rf . >/dev/null 2>&1 || true
          find . -maxdepth 1 ! -name .git -exec rm -rf {} +

      - name: Copy index.html + JSONs
        run: |
          cp index.html ./
          cp data/generated/per-country/*.json ./

      - name: Commit & push gh-pages
        run: |
          git add .
          git commit -m "Rebuild gh-pages from main @${GITHUB_SHA}" || echo "No changes to commit"
          git push origin gh-pages --force
